# Intro to Python
<IMG SRC="media/PythonLogo.png" Width=100>

**Lecturer**: Ashish Mahabal<br>
**Jupyter Notebook Author**: Leo Singer, Cameron Hummels, and Ashish Mahabal

This is a Jupyter notebook lesson extending the GROWTH Summer School 2019 and adapted for the NARIT-EACOA 2019 summer workshop.

## Objective
Introduce the user to the history of Python, its basic usage, a few standard libraries, and some basic analysis of photometric data using astropy.

## Key steps
- Variable manipulation
- Lists, arrays, floats, ints, sets, dictionaries
- Conditionals, loops
- Error handling
- Intro to numpy
- Intro to astropy

## Required dependencies

Nominally, you should be able to install the python modules with `pip install <module>`.  The external astromatic packages are easiest installed using package managers (e.g., `rpm`, `apt-get`).

### Python modules
* python 3
* astropy
* numpy
* matplotlib

### External packages
None

## 0. History

Creator: Guido van Russum (1991, 2.0: 2000, 3.0: 2008)
<IMG SRC="media/GuidoVanRussum.png" WIDTH=300>
* Influenced by the language ABC (where he worked in the 1980s)
(Just like R came from S and indeed, C came from B)
* Orthogonality built in
* types: tuples, tables, lists, numbers, text
* Fast text processing - uut had many problems initially
* Originally developed for the Amoeba (OS) - one of Amoeba's aims was for multiple computers to look like a single coherent one.
* Mostly igored until 2001 when in Python 2.2 user defined classes were introduced

* Forced indentation, but not like Fortran (and better editors helped)
* Great for (large) teams - compare perl

* Issues: no declaration, scopes

## I. Introduction

This part of the workshop is about doing astronomical data analysis with the [Python programming language](https://python.org/). **No previous experience with Python is necessary!**

Python is a powerful tool, but it comes into its own as a numerical and data analysis environment with the following packages, which you will definitely want to have:

* **[Matplotlib](https://matplotlib.org)**: plotting interactive or publication-quality figures
* **[Numpy](http://www.numpy.org)**: vectorized arithmetic and linear algebra
* **[Scipy](https://www.scipy.org)**: curated collection of algorithms for root finding, interpolation, integration, signal processing, statistics, linear algebra, and much more
* **[Jupyter Notebook](https://jupyter.org)** (formerly IPython Notebook): the Mathematica-like interface that you are using now (py in Jupyter stands for python), and last but not least
* **[Astropy](https://www.astropy.org/)**: a community library for astronomy.

We'll cover the basics of Python itself and then dive in to some applications to explore each of these packages.

**NOTE:** The purest way of interacting with Python is via its command line interpreter, which looks like this:

![A session in the Python command line interpreter](https://raw.github.com/lpsinger/astropy-tutorial/master/terminal.png)

A relatively new but very powerful way of using Python is through the Jupyter Notebook interface, which like Mathematica allows you to intermingle computer code with generated plots.  You're using one now.

#### The base has very little, so you start with importing this (but not that).
Try it now to understand Python's philosophy (especially ## 2,7,15,16,19).

In [2]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


To reload a module that has been changed (or not)

In [16]:
import importlib
importlib.reload(this)

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


<module 'this' from '/Users/aam/miniconda3/lib/python3.6/this.py'>

<IMG SRC="media/TimPeters.png" WIDTH=300>

#### O-O from the start: everything is an object!

In [5]:
import math
a = math.sin
a(30)

-0.9880316240928618

Use Shift-tab to explore help for the function arguments. Tabs are great!!!!

In [4]:
a()

TypeError: sin() takes exactly one argument (0 given)

* Very fast growing community
* Very large number of modules
* numpy, scipy, astropy, wcs, pandas, tensorflow, keras, ...
* Large dimensional arrays, images, stats, ML
* Sky is the limit ...

<IMG SRC="media/XKCD353PythonFlying.png" WIDTH=500>

#### On to flying (well, lets start with plotting)!

In [3]:
from matplotlib import pyplot as plt
import numpy as np
%matplotlib widget

x = np.linspace(0, 2 * np.pi)
plt.plot(x, np.sin(x))
plt.xlabel('ppm caffeine in bloodstream')
plt.ylabel('cheeriness')

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Text(0, 0.5, 'cheeriness')

and tables...

In [6]:
import astropy.table
tbl = astropy.table.Table()
tbl.add_column(astropy.table.Column(data=np.arange(5),
    name='integers'))
tbl.add_column(astropy.table.Column(data=np.arange(5)**2,
    name='their squares'))
tbl

<Table length=5>
integers their squares
 int64       int64    
-------- -------------
       0             0
       1             1
       2             4
       3             9
       4            16

and even notes and typeset mathematics...

> *And God said:*
>
> > $$\nabla \cdot \mathbf{D} = \rho$$
> > $$\nabla \cdot \mathbf{B} = 0$$
> > $$\nabla \times \mathbf{E} = -\frac{\partial\mathbf{B}}{\partial t}$$
> > $$\nabla \times \mathbf{H} = J + \frac{\partial\mathbf{D}}{\partial t}$$
>
> *and there was light.*

This is all very useful for doing interactive data analysis, so we will use the IPython Notebook interface for this tutorial. **WARNING:** I'm spoiling you rotten by doing this.

## II. How to get Python/Matplotlib/Numpy/Scipy/Astropy (if necessary)

Python and all of the packages that we discuss in this tutorial are open source software, so there multiple options for installing them.  <b>But if you followed the instructions on the GROWTH website for downloading/installing these modules, you have already installed these dependencies.  Skip to the next step.</b>

### For Linux/UNIX users

If you have one of the common Linux/UNIX distros (for example, [Ubuntu](https://www.ubuntu.com), [Debian](https://debian.org), or [Fedora](https://fedoraproject.org)), then you probably already have Python and you can get Matplotlib and friends from your package manager.

For example, on Debian or Ubuntu, use:

    $ sudo apt-get install jupyter-notebook python3-matplotlib python3-astropy python3-scipy

### For Mac users

Every version of Mac OS comes with a Python interpreter, but it's slightly easier to obtain Matplotlib and Numpy if you use a package manager such as [MacPorts](https://macports.org), [HomeBrew](https://brew.sh), or [Fink](http://www.finkproject.org). I use MacPorts (and contribute to it, too), so that's what I suggest. Install MacPorts and then do:

    $ sudo port install py37-matplotlib py37-scipy py37-jupyterlab py37-astropy

### For Windows users

Windows does not come with Python, but popular and free builds of Python for Windows include [Anaconda](https://www.anaconda.com/distribution/) and [Canopy](https://www.enthought.com/product/canopy/). Another alternative for Windows is to set up a virtual machine with [VirtualBox](https://www.virtualbox.org) and then install a Linux distribution on that.

## III. Python basics

### The `print()` function and string literals

If this is your first time looking at Python code, the first thing that you might notice is that it is very easy to understand. For example, to print something to the screen, it's just:

In [22]:
print('Hello world!')

Hello world!


This is a Python statement, consisting of the built-in command `print` and a string surrounded by single quotes. Double quotes are fine inside a string:

In [23]:
print('She said, "Hello, world!"')

She said, "Hello, world!"


But if you want single quotes inside your string, you had better delimit it with double quotes:

In [24]:
print("She said, 'Hello, world!'")

She said, 'Hello, world!'


If you need both single quotes and double quotes, you can use backslashes to escape characters.

In [25]:
print('She said, "O brave new world, that has such people in\'t!"')

She said, "O brave new world, that has such people in't!"


If you need a string that contains newlines, use triple quotes (`'''`) or triple double quotes (`"""`):

In [7]:
print("""MIRANDA
  O, wonder!
  How many goodly creatures are there here!
  How beauteous mankind is! O brave new world
  That has such people in't!""")

MIRANDA
  O, wonder!
  How many goodly creatures are there here!
  How beauteous mankind is! O brave new world
  That has such people in't!


Let's say that you need to print a few different things on the same line. Just separate them with commas, as in:

In [8]:
person = 'Miranda'
print("'Tis new to", person)

'Tis new to Miranda


Oops. I'm getting ahead of myself—you've now seen your first variable assignment in Python. Strings can be concatened by adding them:

In [9]:
'abc' + 'def'

'abcdef'

Or repeated by multiplying them:

In [10]:
'abcdef' * 2

'abcdefabcdef'

### Numeric and boolean literals

Python's numeric types include integers and both real and complex floating point numbers:

In [11]:
a = 30 # an integer
b = 0xDEADBEEF # an integer in hexadecimal
c = 3.14159 # a floating point number
d = 5.1e10 # scientific notation
e = 2.5 + 5.3j # a complex number
hungry = True # boolean literal
need_coffee = False # another boolean literal

By the way, all of the text on a given line after the trailing hash sign (`#`) is a comment, ignored by Python.

The arithmetic operators in Python are similar to C, C++, Java, and so on. There is addition (and subtraction):

In [12]:
a + c

33.14159

Multiplication:

In [13]:
a * e

(75+159j)

Division:

In [33]:
a / c

9.549304651466295

***Important note***: unlike C, C++, Java, etc., ***division of integers gives you floats***:

In [34]:
7 / 3

2.3333333333333335

If you want integer division, then use the double-slash `//` operator:

In [35]:
a = 7
b = 3
7 // 3

2

The `%` sign is the remainder operator:

In [36]:
32 % 26

6

Exponentiation is accomplished with the `**` operator:

In [37]:
print(5 ** 3, 9**-0.5)

125 0.3333333333333333


### Tuples

A tuple is a sequence of values. It's just about the handiest thing since integers. A tuple is immutable: once you have created it, you cannot add items to it, remove items from it, or change items. Tuples are very handy for storing short sequences of related values or returning multiple values from a function. This is what tuples look like:

In [14]:
some_tuple = ('a', 'b', 'c')
another_tuple = ('caffeine', 6.674e-11, 3.14, 2.718)
nested_tuple = (5, 4, 3, 2, ('a', 'b'), 'c')

Once you have made a tuple, you might want to retrieve a value from it. You index a tuple with square brackets, ***starting from zero***:

In [15]:
some_tuple[0]

'a'

In [40]:
some_tuple[1]

'b'

You can access whole ranges of values using ***slice notation***:

In [41]:
nested_tuple[1:4]

(4, 3, 2)

Or, to count backward from the end of the tuple, use a ***negative index***:

The Last one!


In [16]:
another_tuple[-1]

2.718

In [17]:
another_tuple[-2]

3.14

Strings can be treated just like tuples of individual charaters:

In [18]:
person = 'Miranda'
print(person[3:6])

and


### Lists

What if you want a container like a tuple but to which you can add or remove items or alter existing items? That's a list. The syntax is almost the same, except that you create a list using square brackets `[]` instead of round ones `()`:

In [19]:
your_list = ['foo', 'bar', 'bat', 'baz']
my_list = ['xyzzy', 1, 3, 5, 7]

But you can change elements:

In [20]:
my_list[1] = 2
print(my_list)

['xyzzy', 2, 3, 5, 7]


Or append elements to an existing list:

In [21]:
my_list.append(11)
print(my_list)

['xyzzy', 2, 3, 5, 7, 11]


Or delete elements:

In [29]:
del my_list[0]
print(my_list)

[2, 3, 5, 7, 11]


### Sets

Sometimes you need a collection of items where order doesn't necessarily matter, but each item is guaranteed to be unique. That's a set, created just like a list or tuple but with curly braces `{}`:

In [22]:
a = {5, 6, 'foo', 7, 7, 8}
print(a)

{5, 6, 7, 8, 'foo'}


You can add items to a set:

In [23]:
a.add(3)
print(a)

{3, 5, 6, 7, 8, 'foo'}


Or take them away:

In [32]:
a.remove(3)
print(a)

{5, 6, 7, 8, 'foo'}


You also have set-theoretic intersections with the `&` operator:

In [24]:
{1, 2, 3, 4, 5, 6} & {3, 4}

{3, 4}

And union with the `|` operator:

In [25]:
{1, 2, 3, 4, 5, 6} | {6, 7}

{1, 2, 3, 4, 5, 6, 7}

And set difference with the `-` operator:

In [26]:
{1, 2, 3, 4, 5, 6} - {3, 4}

{1, 2, 5, 6}

### Dictionaries

Sometimes, you want a collection that is like a list, but whose indices are strings or other Python values. That's a dictionary. Dictionaries are handy for any type of database-like operation, or for storing mappings from one set of values to another. You create a dictionary by enclosing a list of key-value pairs in curly braces:

In [27]:
my_grb = {'name': 'GRB 130702A', 'redshift': 0.145, 'ra': (14, 29, 14.78), 'dec': (15, 46, 26.4)}
my_grb

{'name': 'GRB 130702A',
 'redshift': 0.145,
 'ra': (14, 29, 14.78),
 'dec': (15, 46, 26.4)}

You can index items in dictionaries with square braces `[]`, similar to tuples or lists:

In [28]:
my_grb['dec']

(15, 46, 26.4)

or add items to them:

In [29]:
my_grb['url'] = 'http://gcn.gsfc.nasa.gov/other/130702A.gcn3'
my_grb

{'name': 'GRB 130702A',
 'redshift': 0.145,
 'ra': (14, 29, 14.78),
 'dec': (15, 46, 26.4),
 'url': 'http://gcn.gsfc.nasa.gov/other/130702A.gcn3'}

or delete items from them:

In [30]:
del my_grb['url']
my_grb

{'name': 'GRB 130702A',
 'redshift': 0.145,
 'ra': (14, 29, 14.78),
 'dec': (15, 46, 26.4)}

Dictionary keys can be any **immutable** kind of Python object: tuples, strings, integers, and floats are all fine. Values in a dictionary can be **any Python value at all**, including lists or other dictionaries:

In [31]:
{
    'foods': ['chicken', 'veggie burger', 'banana'],
    'cheeses': {'muenster', 'gouda', 'camembert', 'mozarella'},
    (5.5, 2): 42,
    'plugh': 'bat'
}

{'foods': ['chicken', 'veggie burger', 'banana'],
 'cheeses': {'camembert', 'gouda', 'mozarella', 'muenster'},
 (5.5, 2): 42,
 'plugh': 'bat'}

### The `None` object

Sometimes you need to represent the absence of a value, for instance, if you have a gap in a dataset. You might be tempted to use some special value like `-1` or `99` for this purpose, but **don't**! 

Use the built-in object `None`.

In [41]:
a = None

### Conditionals

In Python, control flow statements such as conditionals and loops have blocks indicated with indentation. Any number of spaces or tabs is fine, as long as you are consistent within a block. Common choices include four spaces, two spaces, or a tab.

You can use the `if`...`elif`...`else` statement to have different bits of code run depending on the truth or falsehood of boolean expressions. For example:

In [35]:
a = 3

if a < 3:
    print("i'm in the 'if' block")
    message = 'a is less than 3'
elif a == 3:
    print("i'm in the 'elif' block")
    message = 'a is 3'
else:
    print("i'm in the 'else' block")
    message = 'a is greater than 3'

print(message)

i'm in the 'elif' block
a is 3


You can chain together inequalities just like in mathematical notation:

In [37]:
if 0 < a <= 5:
    print('a is greater than 0 but less than or equal to 5')

a is greater than 0 but less than or equal to 5


You can also combine comparison operators with the boolean `and`, `or`, and `not` operators:

In [38]:
if a < 6 or a > 8:
    print('yahoo!')

yahoo!


In [39]:
if a < 6 and a % 2 == 1:
    print('a is an odd number less than 6!')

a is an odd number less than 6!


In [40]:
if not a == 5: # same as a != 5
    print('a is not 5')

a is not 5


The comparison operator `is` tests whether two Python values are not only equal, but represent the same object. Since there is only one `None` object, the `is` operator is particularly useful for detecting `None`.

In [41]:
food = None

if food is None:
    print('No, thanks')
else:
    print('Here is your', food)

No, thanks


Likewise, there is an `is not` operator:

In [42]:
if food is not None:
    print('Yum!')

The `in` and `not in` operators are handy for testing for membership in a string, set, or dictionary:

In [44]:
if 0 in {1, 2, 3, 4, 5}:
    print('indeed it is')

In [48]:
if 'i' not in 'team':
    print('there is no "i" in "team"')

there is no "i" in "team"


When referring to a dictionary, the `in` operator tests if the item is among the **keys** of the dictionary.

In [49]:
d = {'foo': 3, 'bar': 5, 'bat': 9}
if 'foo' in d:
    print('the key "foo" is in the dictionary')

the key "foo" is in the dictionary


### The `for` and `while` loops

In Python, there are just two types of loops: `for` and `while`. `for` loops are useful for repeating a set of statements for each item in a collection (tuple, set, list, dictionary, or string). `while` loops are not as common, but can be used to repeat a set of statements until a boolean expression becomes false.

In [50]:
for i in [0, 1, 2, 3]:
    print(i**2)

0
1
4
9


The built-in function `range`, which returns a list of numbers, is often handy here:

In [52]:
for i in range(4):
    print(i**2)

0
1
4
9


Or you can have the range start from a nonzero value:

In [53]:
for i in range(-2, 4):
    print(i**2)

4
1
0
1
4
9


You can iterate over the keys and values in a dictionary with `.items()`:

In [55]:
for key, val in d.items():
    print(key, '...', val**3)

foo ... 27
bar ... 125
bat ... 729


The syntax of the `while` loop is similar to the `if` statement:

In [56]:
a = 1
while a < 5:
    a = a * 2
    print(a)

2
4
8


### List comprehensions

Sometimes you need a loop to create one list from another. List comprehensions make this very terse. For example, the following `for` loop:

In [57]:
a = []
for i in range(5):
    a.append(i * 10)

[0, 10, 20, 30, 40]


is equivalent to this list comprehension:

In [58]:
a = [i * 10 for i in range(5)]

You can even incorporate conditionals into a list comprehension. The following:

In [61]:
a = []
for i in range(5):
    if i % 2 == 0:
        # i is even
        a.append(i * 10)

can be written as:

In [60]:
a = [i * 10 for i in range(5) if i % 2 == 0]

### Conditional expressions

Conditional expressions are a closely related shorthand. The following:

In [61]:
if 6/2 == 3:
    a = 'foo'
else:
    a = 'bar'

is equivalent to:

In [62]:
a = 'foo' if 6/2 == 3 else 'bar'

### Functions

Functions are created with the `def` statement. A function may either have or not have a `return` statement to send back a return value.

In [63]:
def square(n):
    return n * n

a = square(3)
print(a)

9


If you want to return multiple values from a function, return a tuple. Parentheses around the tuple are optional.

In [65]:
def powers(n):
    return n**2, n**3

print(powers(3))

(9, 27)


If a function returns multiple values, you can automatically unpack them into multiple variables:

In [66]:
square, cube = powers(3)
print(square)

9


If you pass a mutable value such as a list to a function, then **the function may modify that value**. For example, you might implement the Fibonacci sequence like this:

In [67]:
def fibonacci(seed, n):
    while len(seed) < n:
        seed.append(seed[-1] + seed[-2])
    # Note: no return statement

seed = [1, 1]
fibonacci(seed, 10)
print(seed)

[1, 1, 2, 3, 5, 8, 13, 21, 34, 55]


You can also give a function's arguments default values, such as:

In [68]:
def fibonacci(seed, n=6):
    while len(seed) < n:
        seed.append(seed[-1] + seed[-2])
    # Note: no return statement

seed = [1, 1]
fibonacci(seed)
print(seed)

[1, 1, 2, 3, 5, 8]


If a function has a large number of arguments, it may be easier to read if you pass the arguments by keyword, as in:

In [71]:
seq = [1, 1]
fibonacci(seed=seq, n=4)
print (seq)

[1, 1, 2, 3]


## IV. The Python standard library

Python comes with an extensive **[standard library](http://docs.python.org/2/library/index.html)** consisting of individual **modules** that you can opt to use with the `import` statement. For example:

In [69]:
import math
math.sqrt(3)

1.7320508075688772

In [72]:
from math import pi
pi

3.141592653589793

Some particularly useful parts of the Python standard library are:

* [`random`](https://docs.python.org/3/library/random.html): random number generators
* [`pickle`](https://docs.python.org/3/library/pickle.html): read/write Python objects into files
* [`sqlite3`](https://docs.python.org/3/library/sqlite3.html): SQLite database acces
* [`os`](https://docs.python.org/3/library/os.html): operating system services
* [`os.path`](https://docs.python.org/3/library/os.path.html): file path manipulation
* [`subprocess`](https://docs.python.org/3/library/subprocess.html): launch external processes
* [`email`](https://docs.python.org/3/library/email.html): compose, parse, receive, or send e-mail
* [`pdb`](https://docs.python.org/3/library/pdb.html): built-in debugger
* [`re`](https://docs.python.org/3/library/re.html): regular expressions
* [`http`](https://docs.python.org/3/library/http.html): built-in lightweight web client and server
* [`optparse`](https://docs.python.org/3/library/optparse.html): build pretty command-line interfaces
* [`itertools`](https://docs.python.org/3/library/itertools.html): exotic looping constructs
* [`multiprocessing`](https://docs.python.org/3/library/multiprocessing.html): parallel processing

### Error handling

It can be important for your code to be able to handle error conditions. For example, let's say that you are implementing a sinc function:

In [45]:
def sinc(x):
    return math.sin(x) / x

print(sinc(0))

ZeroDivisionError: float division by zero

Oops! We know that by definition $\mathrm{sinc}(0) = 1$ , so we should catch this error:

In [46]:
def sinc(x):
    try:
        result = math.sin(x) / x
    except ZeroDivisionError:
        result = 1
    return result

print(sinc(0))

1


### Reading and writing files

The built-in `open` function opens a file and returns a `file` object that you can use to read or write data. Here's an example of writing data to a file:

In [73]:
myfile = open('myfile.txt', 'w') # open file for writing
myfile.write("red 1\n")
myfile.write("green 2\n")
myfile.write("blue 3\n")
myfile.close()

And here is reading it:

In [74]:
d = {} # create empty dictionary

for line in open('myfile.txt', 'r'): # open file for reading
    color, num = line.split() # break apart line by whitespace
    num = int(num) # convert num to integer
    d[color] = num

print(d)

{'red': 1, 'green': 2, 'blue': 3}


## V. Numpy & Matplotlib

Numpy provides array operations and linear algebra to Python. A Numpy array is a bit like a Python list, but supports elementwise arithmetic. For example:

In [75]:
import numpy as np

x = np.asarray([1, 2, 3, 4, 5])
y = 2 * x
print(y)

[ 2  4  6  8 10]


Numpy arrays may have any number of dimensions:

In [76]:
x = np.asarray([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
y = np.asarray([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
y

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

An array has a certain number of dimensions denoted `.ndim`:

In [77]:
x.ndim

2

and the dimensions' individual lengths are given by `.shape`:

In [82]:
x.shape

(3, 3)

and the total number of elements by `.size`:

In [84]:
x.size

9

By default, multiplication is elementwise:

In [85]:
x * y

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

To perform matrix multiplication, either convert arrays to `np.matrix` or use `np.dot`:

In [82]:
np.asmatrix(x) * np.asmatrix(y)

matrix([[ 30,  24,  18],
        [ 84,  69,  54],
        [138, 114,  90]])

In [83]:
np.dot(x, y)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

You can also perform comparison operations on arrays...

In [84]:
x > 5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

Although a boolean array doesn't directly make sense in an `if` statement:

In [86]:
if x > 5:
    print('oops')

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [87]:
if np.any(x > 5):
    print('at least some elements are greater than 5')

at least some elements are greater than 5


You can use conditional expressions like indices:

In [87]:
x[x > 5] = 5
x

array([[1, 2, 3],
       [4, 5, 5],
       [5, 5, 5]])

Or manipulate individual rows:

In [88]:
x[1, :] = -1
x

array([[ 1,  2,  3],
       [-1, -1, -1],
       [ 7,  8,  9]])

Or individual columns:

In [89]:
x[:, 1] += 100
x

array([[  1, 102,   3],
       [ -1,  99,  -1],
       [  7, 108,   9]])

Other useful features include various random number generators:

In [91]:
from matplotlib import pyplot as plt
#%matplotlib inline
%matplotlib widget

# Plot histogram of 10k normal random variates
plt.hist(np.random.randn(10000))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

(array([   8.,   94.,  410., 1293., 2481., 2816., 1883.,  784.,  203.,
          28.]),
 array([-3.84413224, -3.11328745, -2.38244267, -1.65159789, -0.9207531 ,
        -0.18990832,  0.54093647,  1.27178125,  2.00262604,  2.73347082,
         3.4643156 ]),
 <a list of 10 Patch objects>)

In [93]:
np.random.uniform(low=0, high=2*np.pi)

5.27035340076783

You've already seen a few examples of Matplotlib. If you have used MATLAB, then Matplotlib code may look familiar.

In [102]:
x = np.linspace(-10, 10)
y = 1 / (1 + np.exp(x))
plt.figure()
plt.plot(x, y)
plt.annotate(
    'foo bar', (x[20], y[20]), (50, 5),
    textcoords='offset points',
    arrowprops={'arrowstyle': '->'})
plt.grid()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

## VI. Astropy

Astropy is a core Python package for astronomy. It is formed from the merger of a number of other Python astronomy packages, but also contains a lot of original code. Core features include:

* `astropy.constants`, `astropy.units`: Physical constants, units, and unit conversion
* `astropy.time`: Manipulation of dates and times
* `astropy.coordinates`: Representation of and conversion between astronomical coordinate systems
* `astropy.table`: Tables and gridded data
* `astropy.io.fits`: Manipulating FITS files
* `astropy.io.ascii`: Manipulating ASCII tables of many different formats
* `astropy.io.votable`: Virtual Observatory tables
* `astropy.wcs`: World Coordinate System transformations
* `astropy.cosmology`: Cosmological calculations
* `astropy.stats`: Astrostatistics
* `astropy.modeling`: multi-D model fitting Swiss army knife

The Astropy project also has sevearl ["affiliated packages"](http://www.astropy.org/affiliated/index.html) that have similar design but are maintained separately, including:

* [Photutils](https://photutils.readthedocs.io/): Aperture photometry
* [Astroquery](https://astroquery.readthedocs.io/): Query astronomical databases

Let's experiment by opening up a P48 image. We'll need several modules from the Astropy package for this exercise.

In [95]:
import astropy.coordinates
import astropy.units as u
import astropy.io.fits
import astropy.stats
import astropy.table
import astropy.wcs
import astropy.cosmology
import scipy.optimize
import scipy.odr

I've downloaded a P48 image and put it in the data/ directory.

In [96]:
fits = astropy.io.fits.open('data/PTF_201307021787_i_p_scie_t041723_u016616794_f02_p003486_c11.fits')
fits

Let's grab the first (and only) HDU of this FITS file:

In [97]:
hdu = fits[0]

Then let's take a look at the contents of the header:

In [98]:
hdu.header

SIMPLE  =                    T / Fits standard                                  
BITPIX  =                  -32 / FOUR-BYTE SINGLE PRECISION FLOATING POINT      
NAXIS   =                    2 / STANDARD FITS FORMAT                           
NAXIS1  =                 2048 / STANDARD FITS FORMAT                           
NAXIS2  =                 4096 / STANDARD FITS FORMAT                           
ORIGIN  = 'Palomar Transient Factory' / Origin of these image data              
CREATOR = 'Infrared Processing and Analysis Center' / Creator of this FITS file 
TELESCOP= 'P48     '           / Name of telescope                              
INSTRUME= 'PTF/MOSAIC'         / Instrument name                                
OBSERVER= 'KulkarniPTF'        / Observer name and project                      
CCDID   = '11      '           / CCD number (0..11)                             
DATE-OBS= '2013-07-02T04:17:23.555' / UTC shutter time YYYY-MM-DDTHH:MM:SS.SSS  
DATE    = '2013-07-01T21:35:

Now let's plot the image data. But let's use sigma-clipping to pick a nice scale for the image.

In [100]:
mean, median, std = astropy.stats.sigma_clipped_stats(hdu.data)

In [101]:
plt.figure(figsize=(20, 10))
plt.imshow(hdu.data, vmin=mean-std, vmax=mean+3*std, cmap='binary')
plt.xlabel('pixel $x$')
plt.ylabel('pixel $y$')

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Text(0, 0.5, 'pixel $y$')

I happen to know that there is something interesting to look at near $\mathrm{RA, Dec}=14^\mathrm{h}29^{m}14.781^{s}, +15^\circ46^\prime26.385^{\prime\prime}$. Let's open the catalog file from IPAC and find this object.

In [103]:
catalog_filename = 'data/PTF_201307021787_c_p_scie_t041723_u016616794_f02_p003486_c11.ctlg.gz'
catalog_table = astropy.table.Table.read(catalog_filename)
catalog_table

<Table length=3677>
  NUMBER   FLAGS XWIN_IMAGE YWIN_IMAGE ...  FLUX_PETRO  FLUXERR_PETRO ZEROPOINT
                    pix        pix     ...      ct            ct               
  int32    int16  float64    float64   ...   float32       float32     float32 
---------- ----- ---------- ---------- ... ------------ ------------- ---------
         1    28   2043.074    214.094 ... 1.010962e+07      2991.671 27.846247
         2     4     65.380    121.919 ...      1643842      1118.459 27.824438
         3     0    983.166     38.558 ...     34078.66      806.3724 27.827711
         4    24    347.435     11.880 ...     97637.42      1273.242 27.829847
         5     0   1419.644     16.543 ...     208834.9      453.9077 27.834558
         6     0    514.564     10.706 ...     1151.076      148.5741 27.824036
         7    16    681.212      6.826 ...     31196.84       314.963  27.82548
         8    17   1702.202      3.995 ...     1736.771       275.431  27.84032
         9    16   1462.955      4.041 ...     74.95251      205.9214 27.834024
       ...   ...        ...        ... ...          ...           ...       ...
      3668     0    633.149   3001.570 ...       629.93      150.1085 27.823418
      3669     0   1349.198   2992.668 ...     4264.755       257.681 27.827106
      3670     0    480.257   3026.587 ...     3148.517       297.799 27.822645
      3671     0    438.992   3038.134 ...     5518.571      380.4832 27.822363
      3672     0   1200.923   2973.869 ...     679.0667      173.8118 27.827667
      3673     0   1900.714   2959.848 ...      456.535      227.0471 27.843845
      3674     0    871.156   2991.505 ...      82773.5      353.2516 27.826073
      3675     3   1023.866   3017.437 ...     4587.294      367.7406  27.82908
      3676     0   1179.159   3018.957 ...     1961.532      322.9964   27.8279
      3677     0   1662.327   3030.111 ...     1493.354      298.8986 27.834106

Now, let's create a coordinates object to represent the target that we are searching for:

In [104]:
target_coord = astropy.coordinates.SkyCoord(
    '14h29m14.781s +15d46m26.385s')
target_coord

<SkyCoord (ICRS): (ra, dec) in deg
    (217.3115875, 15.77399583)>

Now, let's match this position against the source catalog:

In [105]:
# Coordinates of objects in catalog
catalog_coords = astropy.coordinates.SkyCoord(
    ra=catalog_table['ALPHAWIN_J2000'],
    dec=catalog_table['DELTAWIN_J2000'])

# Do source matching
index, separation, distance = target_coord.match_to_catalog_sky(catalog_coords)
index, separation

(array(3259), <Angle [4.20500043e-06] deg>)

Here is the closest-matching row:

In [106]:
index = np.asscalar(index)
matching_row = catalog_table[index]

In [107]:
plt.figure(figsize=(10, 10))
plt.imshow(hdu.data, vmin=mean-std, vmax=mean+3*std, cmap='binary', interpolation='nearest')
plt.xlim(matching_row['XWIN_IMAGE'] - 64, matching_row['XWIN_IMAGE'] + 64)
plt.ylim(matching_row['YWIN_IMAGE'] - 64, matching_row['YWIN_IMAGE'] + 64)

# I happen to know that these images are upside down; use APLPy or the like to
# automatically orient North upward
plt.gca().invert_yaxis()

plt.xlabel('pixel $x$')
plt.ylabel('pixel $y$')

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Text(0, 0.5, 'pixel $y$')

Let's calibrate the Sextractor photometry. We'll query the [PTF photometric calibrator catalog](http://irsa.ipac.caltech.edu/cgi-bin/Gator/nph-scan?projshort=Contributed_Data_Sets) at [IRSA](http://irsa.ipac.caltech.edu/) using [Astroquery](http://astroquery.readthedocs.org/)...

In [111]:
from astroquery.irsa import Irsa

calib_table = Irsa.query_region(
    target_coord,
    catalog='ptfphotcalcat',
    radius=200*u.arcsec)
calib_table

<Table masked=True length=19>
    ra        dec         clon         clat     ...  flag    dist      angle   
   deg        deg                               ...         arcsec      deg    
 float64    float64      object       object    ... int64  float64    float64  
---------- ---------- ------------ ------------ ... ----- ---------- ----------
217.310789  15.772086 14h29m14.59s 15d46m19.51s ...     1   7.428213 201.936592
217.298347  15.759781 14h29m11.60s 15d45m35.21s ...     1  68.740981 221.872219
217.325504  15.788647 14h29m18.12s 15d47m19.13s ...     1  71.441115   42.43006
217.290852  15.770452 14h29m09.80s 15d46m13.63s ...     1  72.972506 259.922078
217.316083  15.752775 14h29m15.86s 15d45m09.99s ...     1  77.979509 168.484482
217.293844  15.788367 14h29m10.52s 15d47m18.12s ...     1  80.340374 310.076374
217.341936  15.781173 14h29m22.06s 15d46m52.22s ...     1 108.254667  76.195635
217.298534  15.802011 14h29m11.65s 15d48m07.24s ...     1 110.518047 335.844641
217.280035  15.768564 14h29m07.21s 15d46m06.83s ...     1  111.05929 259.855291
217.279193  15.755032 14h29m07.01s 15d45m18.12s ...     1 131.381738 238.689357
217.293286  15.806913 14h29m10.39s 15d48m24.89s ...     1 134.386258 331.849195
217.270767  15.767673 14h29m04.98s 15d46m03.62s ...     1 143.252977   260.8567
217.344082  15.749366 14h29m22.58s 15d44m57.72s ...     1 143.308281  128.22579
217.268123  15.768260 14h29m04.35s 15d46m05.74s ...     1 152.001619 262.192586
217.278521  15.746038 14h29m06.85s 15d44m45.74s ...     1 152.512542 228.702158
217.274578  15.745016 14h29m05.90s 15d44m42.06s ...     1 165.322266 230.870344
217.295918  15.729915 14h29m11.02s 15d43m47.69s ...     1 167.738282 198.890243
217.349143  15.806507 14h29m23.79s 15d48m23.43s ...     1 174.980335  48.021103
217.322520  15.826148 14h29m17.40s 15d49m34.13s ...     1 191.512624   11.40079

Let's look at where these are in relation to are target. We'll need to convert the RA, Dec in the table to pixel coordinates. That's where the World Coordinate System (WCS) transformation comes in.

In [114]:
wcs = astropy.wcs.WCS(hdu.header)

In [116]:
plt.figure(figsize=(10, 10))
ax = plt.axes(projection=wcs)
ax.imshow(hdu.data, vmin=mean-std, vmax=mean+3*std, cmap='binary')
ax.set_xlim(matching_row['XWIN_IMAGE'] - 256, matching_row['XWIN_IMAGE'] + 256)
ax.set_ylim(matching_row['YWIN_IMAGE'] - 256, matching_row['YWIN_IMAGE'] + 256)

# Note: last argument is 'origin': FITS standard uses 1-based Fortran-like
# indexing, but Python uses 0-based C-like indexing. In this case, we are
# aligning these locations to a Python array, so we want 0-based indexing.

x, y = wcs.all_world2pix(calib_table['ra'], calib_table['dec'], 0)
ax.scatter(x, y, facecolor='none', edgecolor='red')

# I happen to know that these images are upside down; use APLPy or the like to
# automatically orient North upward
ax.invert_yaxis()

ax.set_xlabel('pixel $x$')
ax.set_ylabel('pixel $y$')

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [117]:
fig = plt.figure(figsize=(10, 10))
ax = plt.axes(projection=wcs)
ax.set_xlim(matching_row['XWIN_IMAGE'] - 256, matching_row['XWIN_IMAGE'] + 256)
ax.set_ylim(matching_row['YWIN_IMAGE'] - 256, matching_row['YWIN_IMAGE'] + 256)
ax.imshow(
    hdu.data, vmin=mean-std, vmax=mean+3*std,
    cmap='binary')
x, y = wcs.all_world2pix(calib_table['ra'], calib_table['dec'], 0)
ax.scatter(x, y, facecolor='none', edgecolor='red')

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Let's now match the calibration sources with sources in the SExtractor catalog.

In [ ]:
calib_coords = astropy.coordinates.SkyCoord(calib_table['ra'], calib_table['dec'])
indexes, _, _ = calib_coords.match_to_catalog_sky(catalog_coords)

In [ ]:
matches = astropy.table.Table()
matches.add_column(calib_table['rptf'])
matches.add_column(calib_table['rerr'])
matches.add_column(catalog_table[indexes]['MAG_AUTO'])
matches.add_column(catalog_table[indexes]['MAGERR_AUTO'])
matches

In [ ]:
plt.figure(figsize=(8, 8))
plt.errorbar(matches['MAG_AUTO'], matches['rptf'],
    xerr=matches['MAGERR_AUTO'], yerr=matches['rerr'],
    linestyle='none')
plt.xlabel('SExtractor MAG_AUTO')
plt.ylabel('Abs. mag. in photometric calibrator database')
plt.gca().invert_xaxis()
plt.gca().invert_yaxis()
plt.grid()

Now let's do a linear fit. Scipy's orthogonal data regression module, `scipy.odr`, is great for fitting functions with errors in both independent and dependent variables.

In [ ]:
data = scipy.odr.RealData(
    x=matches['MAG_AUTO'], sx=matches['MAGERR_AUTO'],
    y=matches['rptf'], sy=matches['rerr'])
odr = scipy.odr.ODR(data, scipy.odr.models.unilinear)
odr.run()

odr.output.pprint()

Let's see what the fit looks like:

In [ ]:
plt.figure(figsize=(8, 8))
plt.errorbar(matches['MAG_AUTO'], matches['rptf'],
    xerr=matches['MAGERR_AUTO'], yerr=matches['rerr'],
    linestyle='none')
plt.plot(matches['MAG_AUTO'], odr.model.fcn(odr.output.beta, matches['MAG_AUTO']))
plt.xlabel('SExtractor MAG_AUTO')
plt.ylabel('Abs. mag. in photometric calibrator database')
plt.gca().invert_xaxis()
plt.gca().invert_yaxis()
plt.grid()

Finally, we can evaluate the magnitude of the target:

In [ ]:
mag_R = odr.model.fcn(odr.output.beta, matching_row['MAG_AUTO'])
mag_R

Then, we propagate errors from the fit and from SExtractor's relative magnitude measurement.

In [ ]:
# Jacobian w.r.t. fit parameters
fjacb = odr.model.fjacb(odr.output.beta, np.atleast_1d(matching_row['MAG_AUTO']))
# Jacobian w.r.t. data
fjacd = odr.model.fjacd(odr.output.beta, matching_row['MAG_AUTO'])

# Uncertainty in magnitude due to fit
var = np.dot(fjacb.T, np.dot(odr.output.cov_beta, fjacb))

# Add contribution due to uncertainty in relative photometry
var += np.dot(fjacd.T, np.dot(matching_row['MAGERR_AUTO']**2, fjacd))

# Take square root -> error bar
emag_R = np.asscalar(np.sqrt(var))
emag_R

So, but for color corrections, this source has a magnitude of $17.34 \pm 0.015$.

This is the afterglow of a GRB at a redshift of $z=0.145$. What's its luminosity distance?

In [ ]:
z = 0.145
cosmo = astropy.cosmology.default_cosmology.get()
DL = cosmo.luminosity_distance(z)
DL

Let's convert this to a distance modulus to find the source's absolute magnitude.

In [ ]:
distance_modulus = 5 * np.log10(DL / (10*u.pc))
distance_modulus

Another shortcut:

In [ ]:
cosmo.distmod(z)

And so the absolute magnitude is:

In [ ]:
mag_R - distance_modulus